version: '3'

volumes:
  produto-ms-data: { }
  
services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq-messaging
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root

  produto-ms-postgres:
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_DB: messaging
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - produto-ms-data:/var/lib/postgresql
